# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\007handler',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rservice.proto\"\x1b\n\x0bHandlerName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\x08Priority\x12\x10\n\x08priority\x18\x01 \x01(\x05\"\x10\n\x0eMessageContext\"\x84\x01\n\x05\x45vent\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x34\n\x0f\x65ventProperties\x18\x03 \x03(\x0b\x32\x1b.Event.EventPropertiesEntry\x1a\x36\n\x14\x45ventPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x12\n\x03Log\x12\x0b\n\x03log\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2x\n\x07service\x12!\n\x07getName\x12\x06.Empty\x1a\x0c.HandlerName\"\x00\x12+\n\x0bgetPriority\x12\x0f.MessageContext\x1a\t.Priority\"\x00\x12\x1d\n\x0bhandleEvent\x12\x06.Event\x1a\x04.Log\"\x00\x42\t\n\x07handlerb\x06proto3'
)




_HANDLERNAME = _descriptor.Descriptor(
  name='HandlerName',
  full_name='HandlerName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='HandlerName.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=44,
)


_PRIORITY = _descriptor.Descriptor(
  name='Priority',
  full_name='Priority',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='priority', full_name='Priority.priority', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=74,
)


_MESSAGECONTEXT = _descriptor.Descriptor(
  name='MessageContext',
  full_name='MessageContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=92,
)


_EVENT_EVENTPROPERTIESENTRY = _descriptor.Descriptor(
  name='EventPropertiesEntry',
  full_name='Event.EventPropertiesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Event.EventPropertiesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Event.EventPropertiesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=227,
)

_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='Event.event', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eventProperties', full_name='Event.eventProperties', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EVENT_EVENTPROPERTIESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=227,
)


_LOG = _descriptor.Descriptor(
  name='Log',
  full_name='Log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='log', full_name='Log.log', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=247,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=256,
)

_EVENT_EVENTPROPERTIESENTRY.containing_type = _EVENT
_EVENT.fields_by_name['eventProperties'].message_type = _EVENT_EVENTPROPERTIESENTRY
DESCRIPTOR.message_types_by_name['HandlerName'] = _HANDLERNAME
DESCRIPTOR.message_types_by_name['Priority'] = _PRIORITY
DESCRIPTOR.message_types_by_name['MessageContext'] = _MESSAGECONTEXT
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['Log'] = _LOG
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HandlerName = _reflection.GeneratedProtocolMessageType('HandlerName', (_message.Message,), {
  'DESCRIPTOR' : _HANDLERNAME,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:HandlerName)
  })
_sym_db.RegisterMessage(HandlerName)

Priority = _reflection.GeneratedProtocolMessageType('Priority', (_message.Message,), {
  'DESCRIPTOR' : _PRIORITY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Priority)
  })
_sym_db.RegisterMessage(Priority)

MessageContext = _reflection.GeneratedProtocolMessageType('MessageContext', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGECONTEXT,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:MessageContext)
  })
_sym_db.RegisterMessage(MessageContext)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {

  'EventPropertiesEntry' : _reflection.GeneratedProtocolMessageType('EventPropertiesEntry', (_message.Message,), {
    'DESCRIPTOR' : _EVENT_EVENTPROPERTIESENTRY,
    '__module__' : 'service_pb2'
    # @@protoc_insertion_point(class_scope:Event.EventPropertiesEntry)
    })
  ,
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Event)
  })
_sym_db.RegisterMessage(Event)
_sym_db.RegisterMessage(Event.EventPropertiesEntry)

Log = _reflection.GeneratedProtocolMessageType('Log', (_message.Message,), {
  'DESCRIPTOR' : _LOG,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Log)
  })
_sym_db.RegisterMessage(Log)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)


DESCRIPTOR._options = None
_EVENT_EVENTPROPERTIESENTRY._options = None

_SERVICE = _descriptor.ServiceDescriptor(
  name='service',
  full_name='service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=258,
  serialized_end=378,
  methods=[
  _descriptor.MethodDescriptor(
    name='getName',
    full_name='service.getName',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_HANDLERNAME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getPriority',
    full_name='service.getPriority',
    index=1,
    containing_service=None,
    input_type=_MESSAGECONTEXT,
    output_type=_PRIORITY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='handleEvent',
    full_name='service.handleEvent',
    index=2,
    containing_service=None,
    input_type=_EVENT,
    output_type=_LOG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICE)

DESCRIPTOR.services_by_name['service'] = _SERVICE

# @@protoc_insertion_point(module_scope)
