# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getName = channel.unary_unary(
                '/service/getName',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.HandlerName.FromString,
                )
        self.getPriority = channel.unary_unary(
                '/service/getPriority',
                request_serializer=service__pb2.MessageContext.SerializeToString,
                response_deserializer=service__pb2.Priority.FromString,
                )
        self.handleEvent = channel.unary_unary(
                '/service/handleEvent',
                request_serializer=service__pb2.Event.SerializeToString,
                response_deserializer=service__pb2.Log.FromString,
                )


class serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getPriority(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def handleEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getName': grpc.unary_unary_rpc_method_handler(
                    servicer.getName,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.HandlerName.SerializeToString,
            ),
            'getPriority': grpc.unary_unary_rpc_method_handler(
                    servicer.getPriority,
                    request_deserializer=service__pb2.MessageContext.FromString,
                    response_serializer=service__pb2.Priority.SerializeToString,
            ),
            'handleEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.handleEvent,
                    request_deserializer=service__pb2.Event.FromString,
                    response_serializer=service__pb2.Log.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service/getName',
            service__pb2.Empty.SerializeToString,
            service__pb2.HandlerName.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getPriority(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service/getPriority',
            service__pb2.MessageContext.SerializeToString,
            service__pb2.Priority.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def handleEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service/handleEvent',
            service__pb2.Event.SerializeToString,
            service__pb2.Log.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
